title: Tradovate API Documentation
description: The official documentation for the Tradovate API. Let's build together!
theme: just-the-docs

logo: "/assets/images/tradovate-negative.svg"
color_scheme: tdv

# custom
build: "TDV"
mode: "dev"
