# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tradovate API Documentation
email: alennert@tradovate.com
description: >- # this means to ignore newlines until "baseurl:"
  Learn to integrate the Tradovate REST and WebSocket APIs into your
  own applications using the JavaScript language. Use what you learn
  to create utility applications for trading, automate a trading strategy,
  or even create a large scale, multi-user application. The sky is the limit!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  arlenner

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# just-the-docs specific variables
search_enabled: true
logo: "/assets/images/tradovate-negative.svg"
color_scheme: tdv

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude: [vendor]
